#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RangeSliderViewQs.Resource", IsApplication=true)]

namespace RangeSliderViewQs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int barHeightPercent = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int emptyColor = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int filledColor = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int rangeCount = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int sliderRadiusPercent = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int slotRadiusPercent = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int rsv_another = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int rsv_custom = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int rsv_large = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int rsv_small = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RangeSliderView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 3
			public const int RangeSliderView_barHeightPercent = 3;
			
			// aapt resource value: 2
			public const int RangeSliderView_emptyColor = 2;
			
			// aapt resource value: 1
			public const int RangeSliderView_filledColor = 1;
			
			// aapt resource value: 0
			public const int RangeSliderView_rangeCount = 0;
			
			// aapt resource value: 5
			public const int RangeSliderView_sliderRadiusPercent = 5;
			
			// aapt resource value: 4
			public const int RangeSliderView_slotRadiusPercent = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
